<?php

/**
 * @file
 * ajax_add_to_cart.install file.
 */

/**
 * Implements hook_install().
 */
function ajax_add_to_cart_install() {
  // General settings default configuration.
  variable_set('ajax_add_to_cart_currency_format', 'currency_symbol');

  // Shopping cart default configuration.
  variable_set('ajax_add_to_cart_checkout_redirect', 'cart_page');
  variable_set('ajax_add_to_cart_show_labels', 'label');
  variable_set('ajax_add_to_cart_empty_cart_message', 'Shopping cart is empty');
  variable_set('ajax_add_to_cart_remove_cart', 'link');
  variable_set('ajax_add_to_cart_product_image', 'no_image');
  variable_set('ajax_add_to_cart_product_image_style', 'ajax_add_to_cart_style');
  variable_set('ajax_add_to_cart_display_tax', 'no_display');

  // Cart teaser default configuration.
  variable_set('ajax_add_to_cart_empty_cart_teaser_message', 'Empty');
  variable_set('ajax_add_to_cart_item_suffix_text', 'item');

  // Add to cart message default configuration.
  variable_set('ajax_add_to_cart_display_popup', 'display_popup_message');
  variable_set('ajax_add_to_cart_success_message', 'Item successfully added to cart');
  variable_set('ajax_add_to_cart_popup_product_image_display', 1);
  variable_set('ajax_add_to_cart_popup_product_image_style', 'thumbnail');
  variable_set('ajax_add_to_cart_popup_product_name_display', 1);
  variable_set('ajax_add_to_cart_popup_product_name_label', 'no_display_label');
  variable_set('ajax_add_to_cart_popup_product_quantity_display', 1);
  variable_set('ajax_add_to_cart_popup_product_quantity_label', 'display_label');
  variable_set('ajax_add_to_cart_popup_product_price_display', 1);
  variable_set('ajax_add_to_cart_popup_product_price_label', 'display_label');
  variable_set('ajax_add_to_cart_popup_product_total_display', 1);
  variable_set('ajax_add_to_cart_popup_product_total_label', 'display_label');
  variable_set('ajax_add_to_cart_popup_checkout', 'Go to checkout');
  variable_set('ajax_add_to_cart_popup_continue_shopping', 'Continue shopping');
}

/**
 * Implements hook_uninstall().
 */
function ajax_add_to_cart_uninstall() {
  // Delete the variables.
  variable_del('ajax_add_to_cart_currency_format');
  variable_del('ajax_add_to_cart_checkout_redirect');
  variable_del('ajax_add_to_cart_show_labels');
  variable_del('ajax_add_to_cart_empty_cart_message');
  variable_del('ajax_add_to_cart_remove_cart');
  variable_del('ajax_add_to_cart_product_image');
  variable_del('ajax_add_to_cart_product_image_style');
  variable_del('ajax_add_to_cart_display_tax');
  variable_del('ajax_add_to_cart_empty_cart_teaser_message');
  variable_del('ajax_add_to_cart_item_suffix_text');
  variable_del('ajax_add_to_cart_display_popup');
  variable_del('ajax_add_to_cart_success_message');
  variable_del('ajax_add_to_cart_popup_product_image_display');
  variable_del('ajax_add_to_cart_popup_product_image_style');
  variable_del('ajax_add_to_cart_popup_product_name_display');
  variable_del('ajax_add_to_cart_popup_product_name_label');
  variable_del('ajax_add_to_cart_popup_product_quantity_display');
  variable_del('ajax_add_to_cart_popup_product_quantity_label');
  variable_del('ajax_add_to_cart_popup_product_price_display');
  variable_del('ajax_add_to_cart_popup_product_price_label');
  variable_del('ajax_add_to_cart_popup_product_total_display');
  variable_del('ajax_add_to_cart_popup_product_total_label');
  variable_del('ajax_add_to_cart_popup_checkout');
  variable_del('ajax_add_to_cart_popup_continue_shopping');
}
