<?php

/**
 * @file
 * Ajax add to cart installation file.
 *
 * Delete the variables on module's uninstallation.
 */

/**
 * Implements hook_uninstall().
 */
function dc_ajax_add_cart_uninstall() {
  // Delete the variables.
  variable_del('dc_ajax_add_cart_checkout_redirect');
  variable_del('dc_ajax_add_cart_show_labels');
  variable_del('dc_ajax_add_cart_empty_cart_message');
  variable_del('dc_ajax_add_cart_remove_cart');
  variable_del('dc_ajax_add_cart_hide_empty_cart');
  variable_del('dc_ajax_add_cart_update_quantity');
  variable_del('dc_ajax_add_cart_empty_cart_teaser_message');
  variable_del('dc_ajax_add_cart_item_suffix_text');
  variable_del('dc_ajax_add_cart_display_popup');
  variable_del('dc_ajax_add_cart_success_message');
  variable_del('dc_ajax_add_cart_popup_product_name_display');
  variable_del('dc_ajax_add_cart_popup_product_name_label');
  variable_del('dc_ajax_add_cart_popup_product_quantity_display');
  variable_del('dc_ajax_add_cart_popup_product_quantity_label');
  variable_del('dc_ajax_add_cart_popup_product_price_display');
  variable_del('dc_ajax_add_cart_popup_product_price_label');
  variable_del('dc_ajax_add_cart_popup_product_total_display');
  variable_del('dc_ajax_add_cart_popup_product_total_label');
  variable_del('dc_ajax_add_cart_popup_checkout');
  variable_del('dc_ajax_add_cart_popup_continue_shopping');
}
